### PR TITLE
Add `009-WE3-Lab`

### PR DESCRIPTION
**Pull request by Haleshot**
Address #13 

Description:
- README touchups; root README + adding GitHub rendered note across all folder READMEs.
- Let me know if it's necessary to keep all files relating to the notebook in the folder (or just the README + the main marimo notebook). (Reverted 8e0a1d681104cbe28ecce0812aaf094eed4e497d for now).
- ~~Also facing an issues where the data doesn't really load in the graphs; followed the instructions stated in their [repository](https://github.com/we3lab/valuing-flexibility-from-water). Have raised an issue regarding the same https://github.com/we3lab/valuing-flexibility-from-water/issues/12~~ Edit: Fixed now.

### CODE REVIEW

**Comment by Haleshot** [comment]
@akshayka Let me know if I should add relevant files relating to running the notebook completely; the issue regarding data not showing up in the graphs was just owing to a simple path issue - resolved.

**Comment by akshayka** [comment]
If the assets are required to run the notebook, perhaps we include them?

**Comment by Haleshot** [comment]
> If the assets are required to run the notebook, perhaps we include them?

Yup, made the changes. Hope it's good to go now.

**Comment by akshayka** [comment]
It looks great! Thank you :)

**Comment by akshayka** [comment]
Oh wow, I didn't realize there were so many assets! I will merge this for now, but if you think there are too many assets, for example if the repo size is too large now, you're welcome to remove them.

**Comment by Haleshot** [comment]
> Oh wow, I didn't realize there were so many assets! I will merge this for now, but if you think there are too many assets, for example if the repo size is too large now, you're welcome to remove them.

Yup, that's what I was a little worried about. Can let this be for now.

**Pull request merged**
